### ISSUE TITLE
About the details of 30values.txt

### ISSUE THREAD

**Issue by WindVChen** [WhoTHU/Adversarial_Texture#1]
Hi, 

I have a question how the 30values.txt be generated. I have noticed that many previous work also make use of the txt file, but there is no descriptions about the details. The source article "Accessorize to a crime: Real and stealthy attacks on state-of-the-art face recognition" said that they selected 30 colors which are printable, and I wonder how to metric the printability.

Looking forward to your reply, thank you.

**Comment by WhoTHU** [comment]
We actually didn't use that file for training.

It seems that the authors of the source article selected the colors by printing a grid of different colors and calculating 30 central colors on the corresponding photo. 

See:

https://github.com/mahmoods01/accessorize-to-a-crime/blob/master/aux/attack/printed-palette.png

and

https://github.com/mahmoods01/accessorize-to-a-crime/blob/3c3cae5b353275f12f0b07fd3039a18f607e2933/aux/attack/make_printable_vals_struct.m
