### ISSUE TITLE
如何生产更大的攻击图片？

### ISSUE THREAD

**Issue by Francisapzii** [WhoTHU/Adversarial_Texture#3]
当前的攻击图片，大概是320 x 320。
请问如何生成更大的TCEGA攻击图片，比如3000 x 3000
谢谢。

**Comment by WhoTHU** [comment]
在这里修改args.z_crop_size 的大小到足够大，然后再crop生成的cloth到想要的大小就行了
https://github.com/WhoTHU/Adversarial_Texture/blob/97538ffda5a8c099454e0e522be4e8788ccee31a/evaluation_texture.py#L265
