### ISSUE TITLE
请问将yolov2改成yolov3的代码能否update到这里

### ISSUE THREAD

**Issue by Francisapzii** [WhoTHU/Adversarial_Texture#4]
想看一下使用yolov3生成攻击效果，请问将yolov2改成yolov3的代码能否update到这里？

**Comment by WhoTHU** [comment]
代码应该不会update了，别的模型基本差不多，可以自行修改

**Comment by Ning565** [comment]
请问一下您成功修改了吗，我修改了以后几轮过后都是黑色图片了？

**Comment by Ning565** [comment]
> 代码应该不会update了，别的模型基本差不多，可以自行修改

请问一下您，需要改哪些方面吗，我们修改了trainning_texture的get_detloss函数，让它加载darknet，同时boxes的格式换成了v3的，还需要改些什么呢？

**Comment by WhoTHU** [comment]
> > 代码应该不会update了，别的模型基本差不多，可以自行修改
> 
> 请问一下您，需要改哪些方面吗，我们修改了trainning_texture的get_detloss函数，让它加载darknet，同时boxes的格式换成了v3的，还需要改些什么呢？

训练用的gt框需要重新生成，具体方案在论文中有写到。另外yolov3比较特殊，详见supplementary讨论。使用TC-EGA攻击的时候只选用yolov3前两个分支的框是比较容易训练的。
