### ISSUE TITLE
请问这个算对抗样本攻击吗？

### ISSUE THREAD

**Issue by AsunwithAfterglow** [WhoTHU/Adversarial_Texture#6]
反复看了论文，还是不太明白。如果算，是白盒或者黑盒攻击中的哪一种呢？
万分感谢！

**Comment by WhoTHU** [comment]
当然是对抗样本攻击啊，测试的时候攻击 生成对抗样本过程中用的目标模型 就是白盒，攻击别的没见过的模型就是黑盒的迁移攻击，文章中都有涉及
