### ISSUE TITLE
请问这个生成器网络是DCGAN吗，里面判别器判断的依据是什么

### ISSUE THREAD

**Issue by liuchangshuo** [WhoTHU/Adversarial_Texture#7]

**Comment by WhoTHU** [comment]
您好，这个生成网络和DCGAN并没有关系，其生成器部分是一个全卷积网络，包括隐空间的mapping。其类似判别器的辅助网络实际并非判别器，其依据见文章中的公式推导，实际作用是使生成网络更容易学习到对抗图案分布。
