### ISSUE TITLE
这个对抗纹理在EGA的训来拿阶段每次优化的什么

### ISSUE THREAD

**Issue by wang1528186571** [WhoTHU/Adversarial_Texture#9]
在EGA的训练阶段，每次优化的是adv_patch吗？
            adv_patch = gen.generate(z)

**Comment by WhoTHU** [comment]
优化的是generator的参数

**Comment by wang1528186571** [comment]
但很奇怪的是，我只想在检测损失那里把纹理做出一点改变，其他时候还是用原图片，也就是说只有检测的时候用的是略微变化的纹理，但他的优化直接变的很奇怪，包括在其他算法也是。





------------------ 原始邮件 ------------------
发件人: Zhanhao Hu ***@***.***&gt;
发送时间: 2024年7月30日 06:13
收件人: WhoTHU/Adversarial_Texture ***@***.***&gt;
抄送: wang1528186571 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [WhoTHU/Adversarial_Texture] 这个对抗纹理在EGA的训来拿阶段每次优化的什么 (Issue #9)





 
优化的是generator的参数

**Comment by WhoTHU** [comment]
generator就是用来生成会变化的对抗图案的，如果训练阶段不需要变化的话，就不需要用这个generator

**Comment by wang1528186571** [comment]
> generator就是用来生成会变化的对抗图案的，如果训练阶段不需要变化的话，就不需要用这个generator

感谢大佬的回复，我的想法在下面图片中，也就是说只有这个检测损失有改变 其他都是针对原图片，但他的优化方向就会很奇怪
![img_v3_02da_a31de1e9-dcd8-40f0-bd95-50aae24dffag](https://github.com/user-attachments/assets/0897ca8b-9d35-4a74-9026-e8f458b4e310)
比如用咱们的代码训练TC-EGA在训练EGA阶段，1000轮左右就会有论文中图片的样子，而像我这样做之后，2000轮还是我下面图片这样（黑色背景，上面有带颜色点状），而且尝试几次都是这样
![adv_patches](https://github.com/user-attachments/assets/8ae2969a-1b21-47fa-81f4-66751a3b3e1d)

**Comment by WhoTHU** [comment]
不好意思，这些本代码外的改动，我没有办法帮你解决

**Comment by wang1528186571** [comment]
没关系 非常感谢你的耐心回复





------------------ 原始邮件 ------------------
发件人: Zhanhao Hu ***@***.***&gt;
发送时间: 2024年7月31日 13:15
收件人: WhoTHU/Adversarial_Texture ***@***.***&gt;
抄送: wang1528186571 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [WhoTHU/Adversarial_Texture] 这个对抗纹理在EGA的训来拿阶段每次优化的什么 (Issue #9)





 
不好意思，这些本代码外的改动，我没有办法帮你解决
